apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: bitnami/nginx:latest
        ports:
        - containerPort: 8443
        volumeMounts:
        - name: nginx-config
          mountPath: /opt/bitnami/nginx/conf/server_blocks
      volumes:
      - name: nginx-config
        configMap:
          name: nginx
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
data:
  aws_proxy.conf: |
    server {
        listen       8443 ssl;
        access_log /dev/stdout;

        ssl_certificate      bitnami/certs/server.crt;
        ssl_certificate_key  bitnami/certs/server.key;
        proxy_ssl_verify     off;

        ssl_session_cache    shared:SSL:1m;
        ssl_session_timeout  5m;

        ssl_ciphers  HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers  on;

        location / {
              proxy_pass https://vpc-ai-integration-es-um7d7lubo5mnlpdf7wssy3hkbe.us-east-1.es.amazonaws.com;
        }
      }

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443

