apiVersion: v1
kind: Template
metadata:
  name: assisted-events-scrape
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: assisted-events-scrape
  spec:
    selector:
      matchLabels:
        app: assisted-events-scrape
    replicas: ${{REPLICAS_COUNT}}
    template:
      metadata:
        labels:
          app: assisted-events-scrape
      spec:
        serviceAccountName: assisted-service
        containers:
        - name: assisted-events-scrape
          image: ${IMAGE_NAME}:${IMAGE_TAG}
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 2000Mi
            requests:
              cpu: 300m
              memory: 400Mi
          env:
          - name: REMOTE_SERVICE_URL
            valueFrom:
              secretKeyRef:
                key: ASSISTED_SERVICE_URL
                name: jenkins
          - name: OFFLINE_TOKEN
              valueFrom:
                secretKeyRef:
                  key: OFFLINE_TOKEN_CRED
                  name: jenkins
          - name: ES_SERVER
              valueFrom:
                secretKeyRef:
                  key: endpoint
                  name: assisted-installer-elasticsearch
          - name: ES_INDEX
            value: ${ES_INDEX}
- apiVersion: policy/v1
  kind: PodDisruptionBudget
  metadata:
    labels:
      app: assisted-events-scrape
    name: assisted-events-scrape
  spec:
    minAvailable: 1
    selector:
      matchLabels:
        app: assisted-events-scrape
parameters:
- name: IMAGE_NAME
  value: quay.io/app-sre/assisted-events-scrape
- name: IMAGE_TAG
  value: latest
  required: true
- name: REPLICAS_COUNT
  value: "1"
- name: ES_INDEX
  value: ''
