apiVersion: v1
kind: Template
metadata:
  name: assisted-events-scrape
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: assisted-events-scrape
  spec:
    selector:
      matchLabels:
        app: assisted-events-scrape
    replicas: ${{REPLICAS_COUNT}}
    template:
      metadata:
        labels:
          app: assisted-events-scrape
      spec:
        serviceAccountName: assisted-service
        containers:
        - name: assisted-events-scrape
          image: ${IMAGE_NAME}:${IMAGE_TAG}
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 2000Mi
            requests:
              cpu: 300m
              memory: 400Mi
          envFrom:
            - secretRef:
                name: events-scrape
          env:
          - name: ES_SERVER
            valueFrom:
              secretKeyRef:
                key: endpoint
                name: assisted-installer-elasticsearch
          - name: ES_INDEX
            value: ${ES_INDEX}
- apiVersion: policy/v1
  kind: PodDisruptionBudget
  metadata:
    labels:
      app: assisted-events-scrape
    name: assisted-events-scrape
  spec:
    minAvailable: 1
    selector:
      matchLabels:
        app: assisted-events-scrape
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: kibana
    labels:
      app: kibana
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: kibana
    template:
      metadata:
        labels:
          app: kibana
      spec:
        containers:
        - name: kibana
          image: ${KIBANA_IMAGE}:${KIBANA_TAG}
          ports:
          - containerPort: 5601
          env:
            - name: ELASTICSEARCH_HOSTS
              valueFrom:
                secretKeyRef:
                  key: endpoint
                  name: assisted-installer-elasticsearch
            - name: ELASTICSEARCH_USERNAME
              value: ""
            - name: ELASTICSEARCH_PASSWORD
              value: ""
            - name: ELASTICSEARCH_SSL_VERIFICATIONMODE
              value: none
- apiVersion: v1
  kind: Service
  metadata:
    name: kibana
  spec:
    selector:
      app: kibana
    ports:
      - protocol: TCP
        port: 5601
        targetPort: 5601
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: kibana-proxy
    labels:
      app: kibana-proxy
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: kibana-proxy
    template:
      metadata:
        labels:
          app: kibana-proxy
      spec:
        containers:
        - name: kibana-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy:v7.2.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: http
            timeoutSeconds: 1
          args: ["--provider", "github", "--http-address", "0.0.0.0:3000", "--https-address", "--github-org", "openshift-assisted", "--show-debug-on-error", "--redirect-url", "http://localhost:3000/oauth2/callback"]
          env:
            - name: OAUTH2_PROXY_UPSTREAMS
              value: http://kibana.assisted-installer-integration.svc:5601
            - name: OAUTH2_PROXY_EMAIL_DOMAINS
              value: "*"
            - name: OAUTH2_PROXY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: CLIENT_ID
                  name: kibana-oauth-application
            - name: OAUTH2_PROXY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: CLIENT_SECRET
                  name: kibana-oauth-application
            - name: OAUTH2_PROXY_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  key: COOKIE_SECRET
                  name: kibana-oauth-application
- apiVersion: v1
  kind: Service
  metadata:
    name: kibana-proxy
  spec:
    selector:
      app: kibana-proxy
    ports:
      - protocol: TCP
        port: 3000
        targetPort: 3000

parameters:
- name: IMAGE_NAME
  value: quay.io/app-sre/assisted-events-scrape
- name: IMAGE_TAG
  value: ''
  required: true
- name: REPLICAS_COUNT
  value: "1"
- name: ES_INDEX
  value: ''
- name: KIBANA_IMAGE
  value: quay.io/app-sre/kibana-oss
- name: KIBANA_TAG
  value: 7.10.2

